language: go

sudo: required
services:
  - docker
go:
  - "1.8.x"
  - "1.10.x"
  - master

jobs:
  include:
    - stage: test
      name: "Run test"   
      script:
        - make test
    - stage: build
      name: "Build docker image"
      on:
        branch: master
      script:
        - make docker-build